import os
import glob
import zipfile
import numpy as np
import torch
import matplotlib.pyplot as plt
from training.backbone import ResNetBackbone
from training.sr_head import SRHead
from training.mixture_head import MixtureHead
from inference.pipeline import SUTRAMInferencePipeline
from evaluation.visualization import percentile_stretch

def main():
    print("Generating comparison samples for all patch scenes...")
    
    # Setup directories
    sample_out_dir = "output/sample_patches"
    os.makedirs(sample_out_dir, exist_ok=True)
    
    # Load model
    checkpoint_path = "checkpoints/sutram_final.pth"
    if not os.path.exists(checkpoint_path):
        print("Model weights checkpoints/sutram_final.pth missing. Please run prepare script first.")
        return
        
    checkpoint = torch.load(checkpoint_path, map_location="cpu")
    backbone = ResNetBackbone()
    sr_head = SRHead()
    mix_head = MixtureHead(K=checkpoint["config"]["K_components"])
    
    backbone.load_state_dict(checkpoint["backbone_state_dict"])
    sr_head.load_state_dict(checkpoint["sr_head_state_dict"])
    mix_head.load_state_dict(checkpoint["mixture_head_state_dict"])
    
    pipeline = SUTRAMInferencePipeline(backbone, sr_head, mix_head, K=checkpoint["config"]["K_components"])
    pipeline.eval()
    
    # Find all sample folders
    sample_dirs = sorted(glob.glob("output/patches/*/sample_*"))
    
    for sample_dir in sample_dirs:
        sample_name = os.path.basename(sample_dir)
        print(f"Processing {sample_name}...")
        
        # Load arrays
        tir_200_path = os.path.join(sample_dir, "tir_200m.npy")
        if not os.path.exists(tir_200_path):
            continue
            
        tir_200 = np.load(tir_200_path).squeeze()
        
        # Format input tensor
        input_tensor = torch.from_numpy(tir_200).float()
        if input_tensor.ndim == 2:
            input_tensor = input_tensor.unsqueeze(0).unsqueeze(0)
        elif input_tensor.ndim == 3:
            input_tensor = input_tensor.unsqueeze(0)
            
        with torch.no_grad():
            sr_tir, decode_outs = pipeline(input_tensor)
            
        sr_np = sr_tir.squeeze().numpy()
        pred_rgb = decode_outs["dominant_color"].squeeze().numpy()
        
        # Transpose BGR to RGB for plotting
        pred_rgb_viz = np.moveaxis(pred_rgb, 0, -1)
        
        # Apply percentile stretches
        lr_stretched = percentile_stretch(tir_200)
        sr_stretched = percentile_stretch(sr_np)
        color_stretched = percentile_stretch(pred_rgb_viz)
        
        # Create publication quality figure
        fig, axes = plt.subplots(1, 3, figsize=(15, 5.5), dpi=150, facecolor="#fafafa")
        plt.subplots_adjust(wspace=0.15, bottom=0.1)
        
        axes[0].imshow(lr_stretched, cmap="inferno")
        axes[0].set_title("1. Raw TIR Input\n(Spatial Res: 200m)", fontsize=11, fontweight="bold", pad=8)
        axes[0].axis("off")
        
        axes[1].imshow(sr_stretched, cmap="inferno")
        axes[1].set_title("2. Super-Resolved TIR\n(Spatial Res: 100m)", fontsize=11, fontweight="bold", pad=8)
        axes[1].axis("off")
        
        axes[2].imshow(color_stretched)
        axes[2].set_title("3. Synthesized OLI RGB\n(Spatial Res: 100m)", fontsize=11, fontweight="bold", pad=8)
        axes[2].axis("off")
        
        fig.suptitle(f"SUTRAM Enhancement Pipeline - {sample_name.upper()}", fontsize=13, fontweight="bold", y=0.98)
        
        out_png = os.path.join(sample_out_dir, f"comparison_{sample_name}.png")
        plt.savefig(out_png, bbox_inches="tight", facecolor=fig.get_facecolor(), edgecolor='none')
        plt.close(fig)
        
    # Write README inside the folder
    readme_content = """# SUTRAM Sample Results Deliverables

This archive contains representative visual validation samples generated by the **SUTRAM (Satellite Uncertainty-aware Thermal Reconstruction through Ambiguity Modeling)** pipeline for the Bharatiya Antriksh Hackathon (BAH) 2026.

## Structure of Deliverables
Each image follows the three-column remote sensing journal layout:
`Raw Thermal (200m) → Super-Resolved Thermal (100m) → Colorized Optical RGB (100m)`

## Included Files
- `comparison_sample_000.png`
- `comparison_sample_001.png`
- `comparison_sample_002.png`
- `comparison_sample_003.png`
- `comparison_sample_006.png`
"""
    readme_path = os.path.join(sample_out_dir, "README.md")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(readme_content)
        
    # Zip all generated files
    zip_path = "output/sample_results_submission.zip"
    print(f"Creating zip archive: {zip_path}...")
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zip_file:
        for file_path in glob.glob(os.path.join(sample_out_dir, "*")):
            zip_file.write(file_path, os.path.basename(file_path))
            
    print(f"Zip archive successfully created: {zip_path}")

if __name__ == "__main__":
    main()
